<?php
use App\Http\Controllers\Api\GalleryController;
use App\Http\Controllers\Api\NewsController;
use App\Http\Controllers\Api\DueController;
use App\Http\Controllers\Api\AdministratorController;
use App\Http\Controllers\Api\ExceptionalMemberController;
use App\Http\Controllers\Api\PlatformFeeController;
use App\Http\Controllers\Api\ProjectDueController;
use App\Http\Controllers\Api\AuthController;use App\Http\Controllers\Api\EventController;use App\Http\Controllers\Api\ExcoController;use App\Http\Controllers\Api\MemberController;use App\Http\Controllers\Api\SetAdministratorController;use App\Http\Controllers\Api\SetController;use App\Http\Controllers\Api\SetMemberController;use Illuminate\Support\Facades\Route;

Route::post('/register',[AuthController::class,'register']);
Route::post('/login',[AuthController::class,'login']);
Route::get('/events',[EventController::class,'index']);
Route::get('/events/featured',[EventController::class,'featured']);
Route::get('/excos',[ExcoController::class,'index']);
Route::get('/sets',[SetController::class,'publicIndex']);
Route::get('/gallery',[GalleryController::class,'index']);
Route::get('/news',[NewsController::class,'index']);
Route::get('/news/{article:slug}',[NewsController::class,'show']);
Route::get('/public-members',[MemberController::class,'publicIndex']);
Route::get('/exceptional-members',[ExceptionalMemberController::class,'index']);

Route::middleware('auth:sanctum')->group(function(){
    Route::get('/me',[AuthController::class,'me']);
    Route::post('/logout',[AuthController::class,'logout']);
    Route::get('/members',[MemberController::class,'index']);
    Route::get('/profile',[MemberController::class,'profile']);
    Route::get('/my-set',[SetController::class,'mySet']);
    Route::get('/my-set-excos',[ExcoController::class,'mySet']);
    Route::patch('/profile',[MemberController::class,'updateProfile']);
    Route::post('/profile',[MemberController::class,'updateProfile']);
    Route::get('/dues',[DueController::class,'memberIndex']);
    Route::post('/dues/{due}/payments',[DueController::class,'submit']);
    Route::get('/project-dues',[ProjectDueController::class,'memberIndex']);

    Route::middleware(['role:coordinator,super_admin','admin.audit'])->prefix('set-management')->group(function(){
        Route::get('/dashboard',[SetMemberController::class,'dashboard']);
        Route::get('/members',[SetMemberController::class,'members']);
        Route::get('/excos',[ExcoController::class,'setIndex']);
        Route::get('/exco-candidates',[ExcoController::class,'candidates']);
        Route::post('/excos',[ExcoController::class,'store']);
        Route::post('/excos/{exco}',[ExcoController::class,'update']);
        Route::delete('/excos/{exco}',[ExcoController::class,'destroy']);
        Route::patch('/community-links',[SetController::class,'updateCommunityLinks']);
        Route::get('/dues',[DueController::class,'manage']);
        Route::post('/dues',function(\Illuminate\Http\Request $request,DueController $controller){$request->merge(['type'=>'set']);return $controller->store($request);});
        Route::patch('/dues/{due}',[DueController::class,'update']);
        Route::delete('/dues/{due}',[DueController::class,'destroy']);
        Route::get('/dues/{due}/payments',[DueController::class,'payments']);
        Route::get('/dues/{due}/ledger',[DueController::class,'ledger']);
        Route::post('/due-payments/{payment}/verify',[DueController::class,'verify']);
        Route::post('/due-payments/{payment}/reject',[DueController::class,'reject']);
        Route::patch('/due-payments/{payment}/reconcile',[DueController::class,'reconcile']);
        Route::get('/platform-fees',[PlatformFeeController::class,'setIndex']);
        Route::post('/platform-fees/{fee}/payments',[PlatformFeeController::class,'submit']);
        Route::get('/project-dues',[ProjectDueController::class,'setIndex']);
        Route::post('/project-due-assignments/{assignment}/payments',[ProjectDueController::class,'submit']);
        Route::get('/administrators',[SetAdministratorController::class,'index']);
        Route::get('/administrator-candidates',[SetAdministratorController::class,'candidates']);
        Route::post('/administrators',[SetAdministratorController::class,'store']);
        Route::delete('/administrators/{administrator}',[SetAdministratorController::class,'destroy']);
        Route::get('/pending-members',[SetMemberController::class,'pending']);
        Route::post('/members/{member}/approve',[SetMemberController::class,'approve']);
        Route::post('/members/{member}/reject',[SetMemberController::class,'reject']);
        Route::patch('/members/{member}',[SetMemberController::class,'update']);
    });

    Route::middleware(['role:super_admin','admin.audit'])->prefix('admin')->group(function(){
        Route::get('/administrators',[AdministratorController::class,'index']);
        Route::post('/administrators',[AdministratorController::class,'store']);
        Route::delete('/administrators/{administrator}',[AdministratorController::class,'destroy']);
        Route::get('/audit-logs',[AdministratorController::class,'audits']);
        Route::get('/exceptional-members',[ExceptionalMemberController::class,'manage']);
        Route::post('/exceptional-members',[ExceptionalMemberController::class,'store']);
        Route::post('/exceptional-members/{exceptionalMember}',[ExceptionalMemberController::class,'update']);
        Route::delete('/exceptional-members/{exceptionalMember}',[ExceptionalMemberController::class,'destroy']);
        Route::get('/members',[MemberController::class,'adminIndex']);
        Route::patch('/members/{member}',[MemberController::class,'adminUpdate']);
        Route::post('/members/{member}/approve',[SetMemberController::class,'approve']);
        Route::post('/members/{member}/reject',[SetMemberController::class,'reject']);
        Route::delete('/members/{member}',[SetMemberController::class,'destroy']);
        Route::get('/dues',[DueController::class,'manage']);
        Route::post('/dues',[DueController::class,'store']);
        Route::patch('/dues/{due}',[DueController::class,'update']);
        Route::delete('/dues/{due}',[DueController::class,'destroy']);
        Route::get('/dues/{due}/payments',[DueController::class,'payments']);
        Route::get('/dues/{due}/ledger',[DueController::class,'ledger']);
        Route::post('/due-payments/{payment}/verify',[DueController::class,'verify']);
        Route::post('/due-payments/{payment}/reject',[DueController::class,'reject']);
        Route::patch('/due-payments/{payment}/reconcile',[DueController::class,'reconcile']);
        Route::get('/platform-fees',[PlatformFeeController::class,'manage']);
        Route::post('/platform-fees',[PlatformFeeController::class,'store']);
        Route::patch('/platform-fees/{fee}',[PlatformFeeController::class,'update']);
        Route::get('/platform-fees/{fee}/ledger',[PlatformFeeController::class,'ledger']);
        Route::post('/platform-fee-payments/{payment}/verify',[PlatformFeeController::class,'verify']);
        Route::post('/platform-fee-payments/{payment}/reject',[PlatformFeeController::class,'reject']);
        Route::get('/project-dues',[ProjectDueController::class,'manage']);
        Route::post('/project-dues',[ProjectDueController::class,'store']);
        Route::patch('/project-dues/{project}',[ProjectDueController::class,'update']);
        Route::post('/project-due-payments/{payment}/verify',[ProjectDueController::class,'verify']);
        Route::post('/project-due-payments/{payment}/reject',[ProjectDueController::class,'reject']);
        Route::get('/news',[NewsController::class,'adminIndex']);
        Route::post('/news',[NewsController::class,'store']);
        Route::post('/news/{article}',[NewsController::class,'update']);
        Route::delete('/news/{article}',[NewsController::class,'destroy']);
        Route::get('/events',[EventController::class,'adminIndex']);
        Route::post('/events',[EventController::class,'store']);
        Route::post('/events/{event}',[EventController::class,'update']);
        Route::delete('/events/{event}',[EventController::class,'destroy']);
        Route::get('/gallery',[GalleryController::class,'adminIndex']);
        Route::post('/events/{event}/photos',[GalleryController::class,'upload']);
        Route::patch('/photos/{photo}',[GalleryController::class,'update']);
        Route::delete('/photos/{photo}',[GalleryController::class,'destroy']);
        Route::get('/sets',[SetController::class,'index']);
        Route::post('/sets',[SetController::class,'store']);
        Route::patch('/sets/{set}',[SetController::class,'update']);
        Route::put('/sets/{set}/coordinator',[SetController::class,'assignCoordinator']);
        Route::get('/excos',[ExcoController::class,'adminIndex']);
        Route::get('/exco-candidates',[ExcoController::class,'candidates']);
        Route::post('/excos',[ExcoController::class,'store']);
        Route::post('/excos/{exco}',[ExcoController::class,'update']);
        Route::patch('/excos/{exco}',[ExcoController::class,'update']);
        Route::delete('/excos/{exco}',[ExcoController::class,'destroy']);
    });
});
