import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, CalendarDays, GraduationCap, HandHeart, MapPin, Network, Sparkles, Users } from 'lucide-react';
import { EventFlash } from '@/components/event-flash';

const pillars=[
  {icon:Users,title:'Reconnect',copy:'Find classmates and rebuild meaningful relationships across graduating sets.'},
  {icon:Network,title:'Grow together',copy:'Share opportunities, mentorship and professional connections.'},
  {icon:HandHeart,title:'Give back',copy:'Support the school, its students and projects that create lasting impact.'},
];

export default function Home(){return <>
  <section className="home-hero"><div className="home-hero-orb one"/><div className="home-hero-orb two"/><div className="shell home-hero-grid"><div className="home-hero-copy reveal"><span className="home-kicker"><i/> The official ICGS alumni community</span><h1>Honouring our roots.<br/><em>Building what comes next.</em></h1><p>Reconnect with old classmates, celebrate five decades of excellence and help strengthen the school that shaped us.</p><div className="home-hero-actions"><Link href="/register" className="button home-primary">Join the association <ArrowRight/></Link><Link href="/events" className="home-secondary"><CalendarDays/>50th anniversary event</Link></div><div className="home-trust"><span><b>50</b><small>Years of legacy</small></span><span><b>40+</b><small>Graduating sets</small></span><span><b>One</b><small>Global family</small></span></div></div><div className="home-students"><div className="anniversary-seal"><Sparkles/><b>50</b><span>Years<br/>1976–2026</span></div><Image src="/icgs-students.png" alt="ICGS students in the school uniform" fill priority sizes="(max-width: 850px) 90vw, 48vw"/></div></div></section>
  <EventFlash/>
  <section className="home-intro"><div className="shell home-intro-grid"><div><span className="eyebrow">Welcome home</span><h2>One school.<br/><em>Every generation.</em></h2></div><div><p>ICGS-OSA brings old students together in one trusted community—turning shared memories into connection, opportunity and meaningful service.</p><Link href="/history">Discover our story <ArrowRight/></Link></div></div></section>
  <section className="home-purpose"><div className="shell"><div className="compact-head"><div><span className="eyebrow">Why we gather</span><h2>Belong. Connect. <em>Make an impact.</em></h2></div><p>Everything we build starts with the bonds formed at Igbotako Community Grammar School.</p></div><div className="home-pillars">{pillars.map(({icon:Icon,title,copy},index)=><article key={title}><span>0{index+1}</span><Icon/><h3>{title}</h3><p>{copy}</p><ArrowRight/></article>)}</div></div></section>
  <section className="anniversary-feature"><div className="shell anniversary-grid"><div className="anniversary-art"><Image src="/icgs-50th-anniversary.jpeg" alt="ICGS 50th Anniversary and Reunion announcement" fill sizes="(max-width: 800px) 100vw, 44vw"/></div><div className="anniversary-copy"><span className="eyebrow light-text">The golden gathering · 3–6 September 2026</span><h2>Fifty years of excellence, <em>one unforgettable reunion.</em></h2><p>Join the ICGS alumni family in Igbotako for networking, reminiscences, strategic engagement and alumni recognition.</p><div className="anniversary-meta"><span><CalendarDays/>3–6 September 2026</span><span><MapPin/>Igbotako, Ondo State</span></div><Link href="/events" className="button white">View event details <ArrowRight/></Link></div></div></section>
  <section className="home-legacy"><div className="shell legacy-grid"><div className="legacy-photo"><Image src="/school-gate.png" alt="Igbotako Community Grammar School gate" fill sizes="(max-width: 800px) 100vw, 50vw"/><span>Established 1976</span></div><div><span className="eyebrow">Our shared heritage</span><h2>From Igbotako,<br/><em>to the world.</em></h2><p>For five decades, our school has nurtured minds, shaped character and prepared generations to serve. Every old student carries that legacy forward.</p><blockquote>Knowledge. Character. Service.</blockquote><Link href="/history">Explore our history <ArrowRight/></Link></div></div></section>
  <section className="home-cta"><div className="shell"><GraduationCap/><div><span className="eyebrow light-text">Your chapter continues here</span><h2>Come home to your community.</h2><p>Join verified ICGS old students and stay connected to the people and legacy that matter.</p></div><Link href="/register" className="button white">Become a member <ArrowRight/></Link></div></section>
</>}
