import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, CalendarDays, GraduationCap, HandHeart, Network, Quote, Users } from 'lucide-react';
import { ArrowLink } from '@/components/site';

const pillars=[{icon:Users,title:'Reconnect',copy:'Find old classmates, discover alumni across generations and rebuild lifelong bonds.'},{icon:HandHeart,title:'Give back',copy:'Support scholarships, school projects and initiatives that create lasting impact.'},{icon:Network,title:'Grow together',copy:'Share opportunities, mentor younger alumni and strengthen our professional network.'}];
export default function Home(){return <>
<section className="hero"><div className="hero-photo"/><div className="hero-overlay"/><div className="shell hero-content"><div className="hero-copy reveal"><span className="eyebrow light-text">Since 1979 · Igbotako, Ondo State</span><h1>Our roots run deep.<br/><em>Our future rises together.</em></h1><p>The official home of Igbotako Community Grammar School Old Students Association—reconnecting generations and giving back to the school that shaped us.</p><div className="hero-buttons"><Link href="/register" className="button">Join our community <ArrowRight size={18}/></Link><Link href="/history" className="button ghost">Discover our story</Link></div></div><div className="motto-card float"><Quote/><span>Our timeless motto</span><strong>The Sky is the Limit</strong></div></div><div className="scroll-mark">SCROLL TO DISCOVER</div></section>
<section className="stats"><div className="shell stats-grid"><div><b>1979</b><span>Our founding year</span></div><div><b>45+</b><span>Years of heritage</span></div><div><b>40+</b><span>Graduating sets</span></div><div><b>One</b><span>Global community</span></div></div></section>
<section className="section intro"><div className="shell two-col"><div><span className="eyebrow">Welcome home</span><h2>More than alumni.<br/><em>A family across generations.</em></h2></div><div><p className="lead">The halls we walked and friendships we formed still connect us. ICGS-OSA is where those memories become momentum—uniting old students to celebrate our heritage and shape what comes next.</p><ArrowLink href="/history">Read our story</ArrowLink></div></div></section>
<section className="section soft"><div className="shell"><div className="section-head"><span className="eyebrow">Why we gather</span><h2>A community built for <em>meaningful connection.</em></h2></div><div className="card-grid">{pillars.map(({icon:Icon,title,copy},i)=><article className="feature-card" key={title}><span>0{i+1}</span><Icon/><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
<section className="section heritage"><div className="shell image-copy"><div className="photo-frame"><Image src="/school-gate.png" alt="Igbotako Community Grammar School gate" fill sizes="(max-width: 800px) 100vw, 50vw"/></div><div><span className="eyebrow">Our shared heritage</span><h2>From Igbotako,<br/><em>to the world.</em></h2><p>For decades, our school has nurtured minds, shaped character and prepared generations to serve their communities. Every old student carries a piece of that legacy.</p><blockquote>“Wherever life takes us, ICGS remains the place our stories began.”</blockquote><ArrowLink href="/history">Explore the school history</ArrowLink></div></div></section>
<section className="section events-preview"><div className="shell"><div className="section-head row"><div><span className="eyebrow">Come together</span><h2>What’s happening <em>next.</em></h2></div><ArrowLink href="/events">View all events</ArrowLink></div><div className="event-row"><div className="date"><b>18</b><span>DEC 2026</span></div><div><span className="tag">Annual reunion</span><h3>ICGS-OSA Homecoming & Annual General Meeting</h3><p>Igbotako Community Grammar School · 10:00 AM</p></div><Link href="/events" className="round"><ArrowRight/></Link></div><div className="event-row"><div className="date"><b>04</b><span>APR 2027</span></div><div><span className="tag">Community impact</span><h3>Back-to-School Mentorship Day</h3><p>School Assembly Hall · 9:00 AM</p></div><Link href="/events" className="round"><ArrowRight/></Link></div></div></section>
<section className="cta"><div className="shell"><GraduationCap/><span className="eyebrow light-text">Your chapter continues here</span><h2>Find your people.<br/><em>Strengthen our legacy.</em></h2><p>Join verified ICGS old students from every graduating set in one trusted community.</p><Link href="/register" className="button white">Become a member <ArrowRight size={18}/></Link></div></section></>}
