<?php
namespace App\Http\Controllers\Api;use App\Http\Controllers\Controller;use App\Models\Due;use App\Models\DuePayment;use Illuminate\Http\Request;
class DueController extends Controller{
public function memberIndex(Request $r){$u=$r->user();$dues=Due::where('published',true)->where(fn($q)=>$q->where('type','association')->orWhere(fn($q)=>$q->where('type','set')->where('alumni_set_id',$u->set?->id)))->with(['payments'=>fn($q)=>$q->where('user_id',$u->id)->latest()])->orderByDesc('year')->get();return $dues->map(fn($d)=>$this->summary($d,$u->id));}
public function submit(Request $r,Due $due){abort_if($due->closed||!$due->published,422,'This due is not accepting payments.');$u=$r->user();abort_if($due->type==='set'&&$due->alumni_set_id!==$u->set?->id,403);$data=$r->validate(['amount'=>'required|numeric|min:1','reference'=>'nullable|string|max:120','method'=>'required|in:bank_transfer,cash,other','paid_at'=>'required|date','note'=>'nullable|string|max:1000']);$data['user_id']=$u->id;$data['status']='pending';return response()->json($due->payments()->create($data),201);}
public function manage(Request $r){$q=Due::with('set')->withSum(['payments as verified_total'=>fn($q)=>$q->where('status','verified')],'amount')->withCount(['payments as pending_count'=>fn($q)=>$q->where('status','pending')]);if($r->user()->role!=='super_admin')$q->where('type','set')->where('alumni_set_id',$r->user()->set?->id);return $q->orderByDesc('year')->get();}
public function store(Request $r){$u=$r->user();$data=$r->validate(['type'=>'required|in:association,set','title'=>'required|string|max:150','year'=>'required|integer|min:2000|max:2100','amount'=>'required|numeric|min:1','deadline'=>'nullable|date','description'=>'nullable|string|max:2000','payment_instructions'=>'nullable|string|max:2000','allow_part_payment'=>'boolean','published'=>'boolean']);if($u->role!=='super_admin'){$data['type']='set';$data['alumni_set_id']=$u->set?->id;}elseif($data['type']==='set')$data['alumni_set_id']=$r->validate(['alumni_set_id'=>'required|exists:alumni_sets,id'])['alumni_set_id'];else $data['alumni_set_id']=null;$data['created_by']=$u->id;return response()->json(Due::create($data),201);}
public function payments(Request $r,Due $due){$this->authorizeDue($r,$due);return $due->payments()->with('member:id,name,email,graduating_year')->latest()->get();}
public function verify(Request $r,DuePayment $payment){$this->authorizeDue($r,$payment->due);$payment->update(['status'=>'verified','verified_by'=>$r->user()->id,'verified_at'=>now()]);return $payment->fresh();}
public function reject(Request $r,DuePayment $payment){$this->authorizeDue($r,$payment->due);$payment->update(['status'=>'rejected','verified_by'=>$r->user()->id,'verified_at'=>now()]);return $payment->fresh();}
private function authorizeDue(Request $r,Due $d):void{abort_if($r->user()->role!=='super_admin'&&($d->type!=='set'||$d->alumni_set_id!==$r->user()->set?->id),403);}
private function summary(Due $d,int $id):array{$verified=(float)$d->payments->where('status','verified')->sum('amount');return [...$d->toArray(),'verified_paid'=>$verified,'balance'=>max(0,(float)$d->amount-$verified),'payment_status'=>$verified>=(float)$d->amount?'paid':($verified>0?'part-paid':($d->payments->where('status','pending')->isNotEmpty()?'pending':'unpaid'))];}}
