<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;use App\Models\User;use Illuminate\Http\Request;use Illuminate\Support\Facades\Storage;use Illuminate\Validation\Rule;
class MemberController extends Controller{
public function publicIndex(Request $r){return User::query()->whereIn('status',['verified','active'])->where('privacy->public_directory',true)->when($r->search,fn($q,$v)=>$q->where(fn($n)=>$n->where('name','like',"%$v%")->orWhere('occupation','like',"%$v%")->orWhere('company','like',"%$v%")))->when($r->integer('year'),fn($q,$v)=>$q->where('graduating_year',$v))->orderBy('name')->paginate(24)->through(fn($u)=>['id'=>$u->id,'name'=>$u->name,'graduating_year'=>$u->graduating_year,'occupation'=>$u->occupation,'company'=>$u->company,'location'=>$u->location,'bio'=>$u->bio,'photo_url'=>$u->photo_url,'whatsapp_url'=>($u->privacy['show_whatsapp']??false)&&$u->phone?'https://wa.me/'.preg_replace('/\D/','',$u->phone):null]);}
public function index(Request $request){$user=$request->user();abort_unless(in_array($user->status,['verified','active'],true),403,'Membership verification required.');$year=$user->role==='super_admin'?$request->integer('year'):$user->graduating_year;return User::query()->select(['id','name','graduating_year','occupation','company','location','bio','photo_url','privacy'])->whereIn('status',['verified','active'])->when($year,fn($q,$v)=>$q->where('graduating_year',$v))->when($request->location,fn($q,$v)=>$q->where('location','like',"%$v%"))->when($request->profession,fn($q,$v)=>$q->where('occupation','like',"%$v%"))->orderBy('name')->paginate(24);}
public function adminIndex(Request $request){$query=User::query()->select(['id','name','email','graduating_year','phone','occupation','company','location','photo_url','role','status','created_at'])->when($request->integer('year'),fn($q,$year)=>$q->where('graduating_year',$year))->when($request->status,fn($q,$status)=>$q->where('status',$status))->when($request->search,fn($q,$search)=>$q->where(fn($nested)=>$nested->where('name','like',"%$search%")->orWhere('email','like',"%$search%")));return $query->latest()->paginate(min(100,max(1,$request->integer('per_page',30))));}
public function adminUpdate(Request $request,User $member){abort_if($member->role==='super_admin'&&$member->id!==$request->user()->id,422,'Other Super Admin accounts cannot be changed here.');$data=$request->validate(['name'=>'required|string|max:120','email'=>['required','email','max:255',Rule::unique('users','email')->ignore($member->id)],'graduating_year'=>'nullable|integer|min:1900|max:2100','phone'=>'nullable|string|max:30','occupation'=>'nullable|string|max:120','company'=>'nullable|string|max:120','location'=>'nullable|string|max:120','status'=>'required|in:pending,verified,active,rejected,suspended']);$member->update($data);return response()->json(['message'=>'Member updated.','member'=>$member->fresh()]);}
public function profile(Request $request){return $request->user()->load(['set','activities']);}
public function updateProfile(Request $request){$data=$request->validate(['name'=>'sometimes|string|max:120','phone'=>'nullable|string|max:30','occupation'=>'nullable|string|max:120','company'=>'nullable|string|max:120','location'=>'nullable|string|max:120','bio'=>'nullable|string|max:2000','public_directory'=>'sometimes|boolean','show_whatsapp'=>'sometimes|boolean','photo'=>'sometimes|image|mimes:jpeg,jpg,png,webp|max:5120']);$user=$request->user();if($request->hasFile('photo')){if($user->photo_url&&str_contains($user->photo_url,'/storage/'))Storage::disk('public')->delete(str($user->photo_url)->after('/storage/')->toString());$data['photo_url']=Storage::disk('public')->url($request->file('photo')->store('profiles','public'));}unset($data['photo']);$privacy=$user->privacy??[];$privacy['public_directory']=$request->boolean('public_directory');$privacy['show_whatsapp']=$privacy['public_directory']&&$request->boolean('show_whatsapp');$data['privacy']=$privacy;unset($data['public_directory'],$data['show_whatsapp']);$user->update($data);return response()->json(['message'=>'Profile updated.','user'=>$user->fresh()]);}}
