<?php
namespace App\Http\Controllers\Api;use App\Http\Controllers\Controller;use App\Models\AlumniSet;use App\Models\PlatformFee;use App\Models\PlatformFeePayment;use Illuminate\Http\Request;
class PlatformFeeController extends Controller{
public function setIndex(Request $r){$set=$this->managedSet($r);return PlatformFee::where('published',true)->with(['payments'=>fn($q)=>$q->where('alumni_set_id',$set->id)])->orderByDesc('year')->get()->map(function($fee){$payment=$fee->payments->first();return [...$fee->toArray(),'payment'=>$payment,'payment_status'=>$payment?->status??'unpaid'];});}
public function submit(Request $r,PlatformFee $fee){abort_if(!$fee->published||$fee->closed,422,'This platform fee is not accepting payment.');$set=$this->managedSet($r);$data=$r->validate(['amount'=>'required|numeric','reference'=>'nullable|string|max:120','method'=>'required|in:bank_transfer,cash,other','paid_at'=>'required|date','note'=>'nullable|string|max:1000']);abort_unless((float)$data['amount']===(float)$fee->amount,422,'The full platform fee amount must be submitted.');$existing=$fee->payments()->where('alumni_set_id',$set->id)->first();abort_if($existing&&in_array($existing->status,['pending','verified'],true),422,'A payment already exists for this set and year.');$payment=$fee->payments()->updateOrCreate(['alumni_set_id'=>$set->id],[...$data,'submitted_by'=>$r->user()->id,'status'=>'pending','verified_by'=>null,'verified_at'=>null]);return response()->json($payment,201);}
public function manage(){return PlatformFee::withCount(['payments as paid_sets_count'=>fn($q)=>$q->where('status','verified'),'payments as pending_count'=>fn($q)=>$q->where('status','pending')])->orderByDesc('year')->get();}
public function store(Request $r){$data=$r->validate(['year'=>'required|integer|min:2000|max:2100|unique:platform_fees,year','title'=>'required|string|max:150','amount'=>'required|numeric|min:1','deadline'=>'nullable|date','payment_instructions'=>'nullable|string|max:2000','published'=>'boolean']);$data['created_by']=$r->user()->id;return response()->json(PlatformFee::create($data),201);}
public function update(Request $r,PlatformFee $fee){$data=$r->validate(['title'=>'required|string|max:150','amount'=>'required|numeric|min:1','deadline'=>'nullable|date','payment_instructions'=>'nullable|string|max:2000','published'=>'boolean','closed'=>'boolean']);$fee->update($data);return $fee->fresh();}
public function ledger(PlatformFee $fee){$payments=$fee->payments()->with(['set:id,year','submitter:id,name,email'])->get()->keyBy('alumni_set_id');return AlumniSet::where('active',true)->with('coordinator:id,name,email')->orderByDesc('year')->get()->map(fn($set)=>['set'=>$set,'payment'=>$payments->get($set->id),'status'=>$payments->get($set->id)?->status??'unpaid']);}
public function verify(Request $r,PlatformFeePayment $payment){$payment->update(['status'=>'verified','verified_by'=>$r->user()->id,'verified_at'=>now()]);return $payment->fresh();}
public function reject(Request $r,PlatformFeePayment $payment){$payment->update(['status'=>'rejected','verified_by'=>$r->user()->id,'verified_at'=>now()]);return $payment->fresh();}
private function managedSet(Request $r){$set=$r->user()->administeredSets()->first();abort_unless($set,403,'No graduating set is assigned to this administrator.');return $set;}}
