<?php
namespace App\Http\Controllers\Api;use App\Http\Controllers\Controller;use App\Models\ProjectDue;use App\Models\ProjectDueAssignment;use App\Models\ProjectDuePayment;use Illuminate\Http\Request;
class ProjectDueController extends Controller{
public function memberIndex(Request $r){$set=$r->user()->set;return $set?$this->forSet($set->id):[];}
public function setIndex(Request $r){$set=$this->managedSet($r);return $this->forSet($set->id);}
private function forSet(int $setId){return ProjectDueAssignment::where('alumni_set_id',$setId)->whereHas('project',fn($q)=>$q->where('published',true))->with(['project','payments'=>fn($q)=>$q->latest()])->latest()->get()->map(fn($a)=>$this->summary($a));}
public function manage(){return ProjectDue::with(['assignments.set:id,year','assignments.payments'])->latest()->get()->map(function($p){$assigned=(float)$p->assignments->sum('amount');$paid=(float)$p->assignments->flatMap->payments->where('status','verified')->sum('amount');return [...$p->toArray(),'assigned_total'=>$assigned,'verified_total'=>$paid,'balance'=>$assigned-$paid];});}
public function store(Request $r){$data=$this->validateProject($r);$assignments=$data['assignments'];unset($data['assignments']);$data['created_by']=$r->user()->id;$project=ProjectDue::create($data);foreach($assignments as $row)$project->assignments()->create($row);return response()->json($project->load('assignments.set'),201);}
public function update(Request $r,ProjectDue $project){$data=$this->validateProject($r);$assignments=$data['assignments'];unset($data['assignments']);$project->update($data);foreach($assignments as $row)$project->assignments()->updateOrCreate(['alumni_set_id'=>$row['alumni_set_id']],['amount'=>$row['amount']]);return $project->fresh('assignments.set');}
private function validateProject(Request $r){return $r->validate(['title'=>'required|string|max:150','description'=>'nullable|string|max:3000','deadline'=>'nullable|date','payment_instructions'=>'nullable|string|max:2000','bank_name'=>'nullable|string|max:150','account_name'=>'nullable|string|max:150','account_number'=>'nullable|string|max:30','published'=>'boolean','closed'=>'boolean','assignments'=>'required|array|min:1','assignments.*.alumni_set_id'=>'required|distinct|exists:alumni_sets,id','assignments.*.amount'=>'required|numeric|min:1']);}
public function submit(Request $r,ProjectDueAssignment $assignment){$assignment->load('project');abort_if(!$assignment->project->published||$assignment->project->closed,422,'This project is not accepting payments.');$set=$this->managedSet($r);abort_unless($assignment->alumni_set_id===$set->id,403);$data=$r->validate(['amount'=>'required|numeric|min:1','reference'=>'nullable|string|max:120','method'=>'required|in:bank_transfer,cash,other','paid_at'=>'required|date','note'=>'nullable|string|max:1000']);$verified=(float)$assignment->payments()->where('status','verified')->sum('amount');abort_if((float)$data['amount']>(float)$assignment->amount-$verified,422,'Payment exceeds the outstanding balance.');return response()->json($assignment->payments()->create([...$data,'submitted_by'=>$r->user()->id,'status'=>'pending']),201);}
public function verify(ProjectDuePayment $payment){$payment->update(['status'=>'verified','verified_by'=>request()->user()->id,'verified_at'=>now()]);return $payment->fresh();}
public function reject(ProjectDuePayment $payment){$payment->update(['status'=>'rejected','verified_by'=>request()->user()->id,'verified_at'=>now()]);return $payment->fresh();}
private function summary(ProjectDueAssignment $a){$paid=(float)$a->payments->where('status','verified')->sum('amount');return [...$a->toArray(),'verified_paid'=>$paid,'balance'=>max(0,(float)$a->amount-$paid),'payment_status'=>$paid>=(float)$a->amount?'paid':($paid>0?'part-paid':($a->payments->where('status','pending')->isNotEmpty()?'pending':'unpaid'))];}
private function managedSet(Request $r){$set=$r->user()->administeredSets()->first();abort_unless($set,403,'No graduating set is assigned to this administrator.');return $set;}}
