<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;use App\Models\AlumniSet;use App\Models\User;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class SetAdministratorController{
private function setFor(Request $request):AlumniSet{$user=$request->user();$set=$user->administeredSets()->first();abort_unless($set,403,'You are not assigned to administer a graduating set.');return $set;}
public function index(Request $request){$set=$this->setFor($request);return response()->json(['set'=>['id'=>$set->id,'year'=>$set->year],'administrators'=>$set->administrators()->get(['users.id','name','email','graduating_year','photo_url'])]);}
public function candidates(Request $request){$set=$this->setFor($request);return User::where('graduating_year',$set->year)->whereIn('status',['verified','active'])->whereDoesntHave('administeredSets',fn($q)=>$q->where('alumni_sets.id',$set->id))->orderBy('name')->get(['id','name','email','graduating_year','occupation','photo_url']);}
public function store(Request $request){$set=$this->setFor($request);$actor=$request->user();$actorAssignment=DB::table('alumni_set_admins')->where(['alumni_set_id'=>$set->id,'user_id'=>$actor->id,'active'=>true])->first();abort_unless($actorAssignment?->is_primary||$actor->role==='super_admin',403,'Only the primary Set Admin can appoint assistants.');abort_if($set->administrators()->count()>=3,422,'This set already has the primary administrator and two assistant administrators.');$data=$request->validate(['user_id'=>'required|integer|exists:users,id']);$candidate=User::findOrFail($data['user_id']);abort_unless($candidate->graduating_year===$set->year,422,'An assistant administrator must belong to this graduating set.');abort_unless(in_array($candidate->status,['verified','active'],true),422,'Only an approved member can become a Set Admin.');DB::transaction(function()use($set,$candidate,$actor){DB::table('alumni_set_admins')->updateOrInsert(['alumni_set_id'=>$set->id,'user_id'=>$candidate->id],['assigned_by'=>$actor->id,'is_primary'=>false,'active'=>true,'created_at'=>now(),'updated_at'=>now()]);$candidate->update(['role'=>'coordinator']);});return response()->json(['message'=>'Assistant Set Administrator appointed.'],201);}
public function destroy(Request $request,User $administrator){$set=$this->setFor($request);$actor=$request->user();$actorAssignment=DB::table('alumni_set_admins')->where(['alumni_set_id'=>$set->id,'user_id'=>$actor->id,'active'=>true])->first();abort_unless($actorAssignment?->is_primary||$actor->role==='super_admin',403,'Only the primary Set Admin can remove assistants.');$assignment=DB::table('alumni_set_admins')->where(['alumni_set_id'=>$set->id,'user_id'=>$administrator->id,'active'=>true])->first();abort_unless($assignment,404,'Administrator assignment not found.');abort_if($assignment->is_primary,422,'The primary Set Admin can be changed only by the Super Admin.');DB::transaction(function()use($set,$administrator){DB::table('alumni_set_admins')->where(['alumni_set_id'=>$set->id,'user_id'=>$administrator->id])->update(['active'=>false,'updated_at'=>now()]);if(!$administrator->administeredSets()->exists())$administrator->update(['role'=>'member']);});return response()->json(['message'=>'Assistant Set Administrator removed.']);}}
