<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;use App\Models\AlumniSet;use App\Models\User;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class SetController extends Controller{
public function publicIndex(){return AlumniSet::where('active',true)->orderByDesc('year')->get(['id','year']);}
public function index(){return AlumniSet::with('coordinator:id,name,email')->withCount(['members','members as approved_members_count'=>fn($q)=>$q->whereIn('status',['verified','active']),'members as pending_members_count'=>fn($q)=>$q->where('status','pending')])->orderByDesc('year')->paginate(30);}
public function store(Request $request){$data=$request->validate(['year'=>'required|integer|min:1979|max:'.date('Y').'|unique:alumni_sets,year','description'=>'nullable|string|max:2000','active'=>'boolean']);return response()->json(AlumniSet::create($data),201);}
public function update(Request $request,AlumniSet $set){$data=$request->validate(['description'=>'nullable|string|max:2000','active'=>'boolean']);$set->update($data);return $set->fresh('coordinator');}
public function assignCoordinator(Request $request,AlumniSet $set){$data=$request->validate(['user_id'=>'required|integer|exists:users,id']);$user=User::findOrFail($data['user_id']);abort_unless($user->graduating_year===$set->year,422,'A Set Administrator must belong to the assigned graduating set.');DB::transaction(function()use($set,$user,$request){if($set->coordinator_id&&$set->coordinator_id!==$user->id){DB::table('alumni_set_admins')->where(['alumni_set_id'=>$set->id,'user_id'=>$set->coordinator_id])->update(['is_primary'=>false,'updated_at'=>now()]);}$user->update(['role'=>'coordinator','status'=>'active']);$set->update(['coordinator_id'=>$user->id]);DB::table('alumni_set_admins')->updateOrInsert(['alumni_set_id'=>$set->id,'user_id'=>$user->id],['assigned_by'=>$request->user()->id,'is_primary'=>true,'active'=>true,'created_at'=>now(),'updated_at'=>now()]);});return response()->json(['message'=>'Primary Set Administrator assigned.','set'=>$set->fresh('coordinator')]);}}
