<?php
namespace App\Http\Controllers\Api;use App\Http\Controllers\Controller;use App\Models\MemberActivity;use App\Models\User;use Illuminate\Database\QueryException;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Storage;
class SetMemberController extends Controller{
private function managedYear(Request $request):?int{$user=$request->user();if($user->role==='super_admin')return $request->integer('year')?:null;$set=$user->administeredSets()->first();abort_unless($set,403,'You are not assigned to administer a graduating set.');return $set->year;}
private function scopedMember(Request $request,User $member):User{if($request->user()->role!=='super_admin')abort_unless($this->managedYear($request)===$member->graduating_year,403,'You can manage only members of your assigned set.');return $member;}
public function pending(Request $request){$year=$this->managedYear($request);return User::where('status','pending')->when($year,fn($q,$v)=>$q->where('graduating_year',$v))->oldest()->paginate(24);}
public function approve(Request $request,User $member){$member=$this->scopedMember($request,$member);abort_unless($member->status==='pending',422,'Only pending applications can be approved.');$member->update(['status'=>'active','approved_by'=>$request->user()->id,'approved_at'=>now()]);MemberActivity::create(['user_id'=>$member->id,'type'=>'membership_approved','title'=>'Membership application approved','occurred_at'=>now()]);return response()->json(['message'=>'Member approved.','member'=>$member->fresh()]);}
public function reject(Request $request,User $member){$member=$this->scopedMember($request,$member);$data=$request->validate(['reason'=>'nullable|string|max:1000']);$member->update(['status'=>'rejected']);MemberActivity::create(['user_id'=>$member->id,'type'=>'membership_rejected','title'=>'Membership application was not approved','description'=>$data['reason']??null,'occurred_at'=>now()]);return response()->json(['message'=>'Application rejected.']);}
public function update(Request $request,User $member){$member=$this->scopedMember($request,$member);$data=$request->validate(['name'=>'sometimes|string|max:120','phone'=>'nullable|string|max:30','occupation'=>'nullable|string|max:120','company'=>'nullable|string|max:120','location'=>'nullable|string|max:120','status'=>'sometimes|in:active,suspended']);$member->update($data);return $member->fresh();}
public function destroy(Request $request,User $member){abort_unless($request->user()->role==='super_admin',403,'Only the Super Admin can remove member accounts.');abort_if($member->id===$request->user()->id||$member->role==='super_admin',422,'A Super Admin account cannot be removed here.');$photo=$member->photo_url&&str_contains($member->photo_url,'/storage/')?str($member->photo_url)->after('/storage/')->toString():null;try{DB::transaction(function()use($member){DB::table('payments')->where('confirmed_by',$member->id)->update(['confirmed_by'=>null]);DB::table('payments')->where('user_id',$member->id)->delete();DB::table('alumni_set_admins')->where('user_id',$member->id)->delete();$member->delete();});}catch(QueryException){abort(422,'This account owns association content and cannot be removed until that content is reassigned.');}if($photo)Storage::disk('public')->delete($photo);return response()->json(['message'=>'Member account removed.']);}}
